channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
 # - bcftools=1.3.1
  - bwa=0.7.12
  - graphviz=2.38.0
  - fastqc=0.11.5
  - ucsc-bigwigaverageoverbed
  - picard=2.15.0
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=4.3.0
  - pyyaml=3.11
  - bedtools=2.26.0
  - blat
  - pandas=0.21.1
  - r-essentials
  - r-plyr
  - r-devtools
  - r-splitstackshape
  - r-circlize
  - r-MASS
  - r-R.cache
  - r-gtools
  - r-survival
  - r-ggplot2
  - bioconductor-qdnaseq=1.10.0
  - bioconductor-biomart
  - bioconductor-VariantAnnotation
  - bioconductor-bsgenome
  - bioconductor-CGHregions
  - bioconductor-TxDb.Hsapiens.UCSC.hg19.knownGene
  - bioconductor-org.Hs.eg.db
  - perl-bioperl
  - perl-dbd-mysql
  - pysam
