channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
 # - bcftools=1.3.1
  - bwa=0.7.12
  - graphviz=2.38.0
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - bedtools=2.26.0
  - r-essentials
  - r-plyr
  - bioconductor-biomart
  - r-splitstackshape
  - bioconductor-VariantAnnotation
  - r-devtools
